name: "stats_metricsinroi"
description: Module to compute statistics (mean, std) of scalar maps (metrics), which
  can represent diffusion metrics, in ROIs or labels.
keywords:
  - nifti
  - volume
  - scilpy
  - stats
  - rois
tools:
  - scilpy:
      description: The Sherbrooke Connectivity Imaging Lab (SCIL) Python dMRI processing
        toolbox.
      homepage: https://github.com/scilus/scilpy.git
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'test', single_end:false ]`
    - metrics:
        type: file
        description: Metrics volume(s) in Nifti
        pattern: "*.{nii,nii.gz}"
        ontologies:
          - edam: http://edamontology.org/format_4001 # NIFTI format
    - rois:
        type: file
        description: ROI or Label volume(s) in Nifti
        pattern: "*.{nii,nii.gz}"
        ontologies:
          - edam: http://edamontology.org/format_4001 # NIFTI format
    - rois_lut:
        type: file
        description: LUT file corresponding to labels, used to name the regions of interest
        pattern: "*.{nii,nii.gz}"
        mandatory: false
        ontologies:
          - edam: http://edamontology.org/format_4001 # NIFTI format
args:
  - suffix:
      type: string
      description: It will add an extra string before "_stats.json"
      default: ""
  - bin:
      type: boolean
      description: |
        If set, will consider every value of the mask higherthan 0 to be
        part of the mask (equivalent weighting for every voxel).
        It will be used if use_label is false.
      default: false
  - normalize_weights:
      type: boolean
      description: |
        If set, the weights will be normalized to the [0,1] range.
        It will be used if use_label is false.
      default: false
  - use_label:
      type: boolean
      description: If set, rois image will be considered as a label image with multiple
        indices.
      default: false
  - key_substrs_to_remove:
      type: string
      description: |
        Groovy list of strings to remove from the metric keys in the JSON.
        This is useful to clean or shorten the bundle names that will appear
        in the output JSON/CSV.
        e.g. "['_mask', '_warped'] will turn 'CST_mask_warped' into 'CST'"
      default: null
  - value_substrs_to_remove:
      type: string
      description: |
        Groovy list of strings to remove from the metric values in the JSON.
        This is useful to clean or shorten the metric names that will appear
        in the output JSON/CSV.
        e.g. "['sub-01', '_metric'] will turn 'sub-01_fa_metric' into 'fa'"
      default: null
  - output_format:
      type: string
      description: |
        Output format for the tabular stats file.
      choices:
        - "csv"
        - "tsv"
      default: "tsv"

output:
  stats_json:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*_stats.json":
          type: file
          description: JSON file containing mean/std per pair of roi/metrics or label/metrics
          pattern: "*_stats.json"
          ontologies:
            - edam: http://edamontology.org/format_3464 # JSON
  stats_tab:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*_stats.{csv,tsv}":
          type: file
          description: Tabular file containing rows of (sid, bundle, metric, mean, std). Can be
            either TSV or CSV depending on the output_format argument.
          pattern: "*_stats.{csv,tsv}"
          ontologies:
            - edam: http://edamontology.org/format_3752 # CSV
            - edam: http://edamontology.org/format_3475 # TSV

  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: "versions.yml"
        ontologies:
          - edam: http://edamontology.org/format_3750 # YAML
authors:
  - "@arnaudbore"
