name: "topup_eddy"
description: |
  Subworkflow performing distorsions correction/eddy correction/motion correction.
  If a reverse B0 or a reverse DWI is provided it will run topup and then eddy,
  otherwise only eddy will run.

  ---------  Steps  --------------------

  1. PREPROC_TOPUP (topup, FSL)
    Prepare data and apply FSL topup
  2. PREPROC_EDDY (eddy, FSL)
    Apply Eddy (and Topup if already run)
  3. UTILS_EXTRACTb0 (scilpy, scilus)
    Extract a b0 volume from a DWI image.
keywords:
  - preprocessing
  - dwi
  - topup
  - eddy
  - distorsion
  - extract_b0
components:
  - preproc/topup
  - preproc/eddy
  - utils/extractb0
  - betcrop/fslbetcrop
input:
  - ch_dwi:
      type: file
      description: |
        The input channel containing the DWI file, B-values and B-vectors in FSL format files.
        Structure: [ val(meta), path(dwi), path(bval), path(bvec) ]
      pattern: "*{.nii,.nii.gz,.bval,.bvec}"
  - ch_b0:
      type: file
      description: |
        The input channel containing the b0 reference for the DWI.
        Structure: [ val(meta), path(b0) ]
      pattern: "*{.nii,.nii.gz}"
      mandatory: false
  - ch_rev_dwi:
      type: file
      description: |
        The input channel containing the reverse DWI file, B-values and B-vectors in FSL format files.
        Structure: [ val(meta), path(rev_dwi), path(bval), path(bvec) ]
      pattern: "*{.nii,.nii.gz,.bval,.bvec}"
      mandatory: false
  - ch_rev_b0:
      type: file
      description: |
        The input channel containing the reverse b0 file.
        Structure: [ val(meta), path(rev_b0) ]
      pattern: "*{.nii,.nii.gz}"
      mandatory: false
  - config_topup:
      type: file
      description: |
        Topup config file. Optional. See https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/topup/TopupUsersGuide#Configuration_files
        Structure: [ path(config_topup) ]
      pattern: "*cnf"
      mandatory: false
output:
  - dwi:
      type: file
      description: |
        Nifti volume - DWI corrected
        Structure: [ val(meta), path(dwi) ]
      pattern: "*__dwi_corrected.nii.gz"
  - bval:
      type: file
      description: |
        B-values corrected in FSL format
        Structure: [ val(meta), path(bval) ]
      pattern: "*__bval_eddy"
  - bvec:
      type: file
      description: |
        B-vectors corrected in FSL format
        Structure: [ val(meta), path(bvec) ]
      pattern: "*__dwi_eddy_corrected.bvec"
  - b0:
      type: file
      description: |
        Nifti volume - b0 corrected
        Structure: [ val(meta), path(b0) ]
      pattern: "*__b0_mask.nii.gz"
  - b0_mask:
      type: file
      description: |
        Nifti volume - Mask for b0 corrected
        Structure: [ val(meta), path(b0_mask) ]
      pattern: "*__b0_bet_mask.nii.gz"
  - mqc:
      type: file
      description: |
        Channel containing the quality control images for MultiQC.
        Structure: [ path(mqc), ... ]
      pattern: "*_mqc.{gif,png}"
      mandatory: false
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@arnaudbore"
