# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "reconst_fw_noddi"
description: |
  Sub-workflow that runs both RECONST/NODDI and RECONST/FREEWATER modules by
  handling the conditional execution of the diffusivity priors. Single-value
  diffusivity priors can be specified as input to this subworkflow. If not
  specified, the subworkflow will compute the priors automatically. They can
  then be averaged using the average_diff_priors argument of this workflow.

keywords:
  - multi-shell
  - freewater
  - noddi
  - diffusion
components:
  - reconst/noddi
  - reconst/freewater
  - reconst/diffusivitypriors
  - reconst/meandiffusivitypriors
  - reconst/dtimetrics
input:
  - dwi_bval_bvec:
      type: file
      description: |
        The input channel containing the DWI, BVAL, and BVEC files.
        Structure: [ val(meta), path(dwi), path(bval), path(bvec) ]
      pattern: "*.{dwi,bval,bvec}"
  - brain_mask:
      type: file
      description: |
        The input channel containing the brain mask file (e.g. b0_mask).
        Structure: [ val(meta), path(brain_mask) ]
      pattern: "*.nii.gz"
  - fa_ad_rd_md:
      type: file
      description: |
        The input channel containing DTI metrics (FA, AD, RD, MD). Not used
        when supplying custom diffusivity priors.
        Structure: [ val(meta), path(fa), path(ad), path(rd), path(md) ]
      pattern: "*.nii.gz"
      mandatory: false
  - diffusivities:
      type: Map
      description: |
        The input channel containing custom diffusivity priors to use for NODDI
        and FreeWater models. If not provided, the diffusivity priors will be
        computed automatically. Can be subject-bound (i.e. different values per
        subject), a single-value for all subjects, or empty to compute them
        automatically. IMPORTANT: all priors must be provided the same way,
        meaning that if one prior is subject-bound, all others must be subject-bound
        as well (same for single-value or empty).
        Structure: [
          para_diff: channel.empty(),     // Example of empty to compute automatically
          iso_diff: channel.value(0.003), // Example of single-value for all subjects
          perp_diff_min: channel.of(      // Example of subject-bound values
            tuple([ id:'subj1' ], 0.0001),
            tuple([ id:'subj2' ], 0.00015)
          ),
          perp_diff_max: channel.of(
            tuple([ id:'subj1' ], 0.0007),
            tuple([ id:'subj2' ], 0.00065)
          )
        ]
      mandatory: false
args:
  - run_noddi:
      type: boolean
      default: false
      description: |
        Whether to run the NODDI reconstruction.
  - run_freewater:
      type: boolean
      default: false
      description: |
        Whether to run the FreeWater correction.
  - average_diff_priors:
      type: boolean
      default: false
      description: |
        Whether to average the diffusivity priors computed from the
        RECONST/DIFFUSIVITYPRIORS module across all subjects. (Recommended)
output:
  - noddi_dir:
      type: file
      description: |
        Nifti file main direction.
        Structure: [ val(meta), path(dir) ]
      pattern: "*__fit_dir.nii.gz"
      mandatory: false
  - noddi_isovf:
      type: file
      description: |
        Nifti file for isotropic volume fraction.
        Structure: [ val(meta), path(isovf) ]
      pattern: "*__isovf.nii.gz"
      mandatory: false
  - noddi_icvf:
      type: file
      description: |
        Nifti file for intracellular volume fraction.
        Structure: [ val(meta), path(icvf) ]
      pattern: "*__icvf.nii.gz"
      mandatory: false
  - noddi_ecvf:
      type: file
      description: |
        Nifti file for Extra-Cellular Volume Fraction.
        Structure: [ val(meta), path(ecvf) ]
      pattern: "*__ecvf.nii.gz"
      mandatory: false
  - noddi_odi:
      type: file
      description: |
        Nifti file for Orientation Dispersion Index.
        Structure: [ val(meta), path(odi) ]
      pattern: "*__odi.nii.gz"
      mandatory: false
  - fw_dwi:
      type: file
      description: |
        Free Water corrected DWI Nifti file.
        Structure: [ val(meta), path(fw_dwi) ]
      pattern: "*__dwi_fw_corrected.nii.gz"
      mandatory: false
  - fw_dir:
      type: file
      description: |
        Free Water corrected main direction Nifti file.
        Structure: [ val(meta), path(fw_dir) ]
      pattern: "*__dir.nii.gz"
      mandatory: false
  - fw_fibervolume:
      type: file
      description: |
        Free Water corrected fiber volume Nifti file.
        Structure: [ val(meta), path(fw_fibvolume) ]
      pattern: "*__fibervolume.nii.gz"
      mandatory: false
  - fw_fwf:
      type: file
      description: |
        Free Water corrected Free Water Fraction Nifti file.
        Structure: [ val(meta), path(fw_fwf) ]
      pattern: "*__fwf.nii.gz"
      mandatory: false
  - fw_nrmse:
      type: file
      description: |
        Free Water correction NRMSE Nifti file.
        Structure: [ val(meta), path(fw_nrmse) ]
      pattern: "*__nrmse.nii.gz"
      mandatory: false
  - fw_dti_tensor:
      type: file
      description: |
        Free Water corrected DTI tensor Nifti file.
        Structure: [ val(meta), path(fw_dti_tensor) ]
      pattern: "*__tensor.nii.gz"
      mandatory: false
  - fw_dti_md:
      type: file
      description: |
        Free Water corrected DTI Mean Diffusivity Nifti file.
        Structure: [ val(meta), path(fw_dti_md) ]
      pattern: "*__md.nii.gz"
      mandatory: false
  - fw_dti_rd:
      type: file
      description: |
        Free Water corrected DTI Radial Diffusivity Nifti file.
        Structure: [ val(meta), path(fw_dti_rd) ]
      pattern: "*__rd.nii.gz"
      mandatory: false
  - fw_dti_ad:
      type: file
      description: |
        Free Water corrected DTI Axial Diffusivity Nifti file.
        Structure: [ val(meta), path(fw_dti_ad) ]
      pattern: "*__ad.nii.gz"
      mandatory: false
  - fw_dti_fa:
      type: file
      description: |
        Free Water corrected DTI Fractional Anisotropy Nifti file.
        Structure: [ val(meta), path(fw_dti_fa) ]
      pattern: "*__fa.nii.gz"
      mandatory: false
  - fw_dti_rgb:
      type: file
      description: |
        Free Water corrected DTI RGB Nifti file.
        Structure: [ val(meta), path(fw_dti_rgb) ]
      pattern: "*__rgb.nii.gz"
      mandatory: false
  - fw_dti_peaks:
      type: file
      description: |
        Free Water corrected DTI Peaks Nifti file.
        Structure: [ val(meta), path(fw_dti_peaks) ]
      pattern: "*__evec_v1.nii.gz"
      mandatory: false
  - fw_dti_evecs:
      type: file
      description: |
        Free Water corrected DTI Eigenvectors Nifti file.
        Structure: [ val(meta), path(fw_dti_evecs) ]
      pattern: "*__evecs.nii.gz"
      mandatory: false
  - fw_dti_evals:
      type: file
      description: |
        Free Water corrected DTI Eigenvalues Nifti file.
        Structure: [ val(meta), path(fw_dti_evals) ]
      pattern: "*__evals.nii.gz"
      mandatory: false
  - fw_dti_residual:
      type: file
      description: |
        Free Water corrected DTI Residuals Nifti file.
        Structure: [ val(meta), path(fw_dti_residual) ]
      pattern: "*__residual.nii.gz"
      mandatory: false
  - fw_dti_ga:
      type: file
      description: |
        Free Water corrected DTI Geodesic Anisotropy Nifti file.
        Structure: [ val(meta), path(fw_dti_ga) ]
      pattern: "*__ga.nii.gz"
      mandatory: false
  - fw_dti_mode:
      type: file
      description: |
        Free Water corrected DTI Mode Nifti file.
        Structure: [ val(meta), path(fw_dti_mode) ]
      pattern: "*__mode.nii.gz"
      mandatory: false
  - fw_dti_norm:
      type: file
      description: |
        Free Water corrected DTI Norm Nifti file.
        Structure: [ val(meta), path(fw_dti_norm) ]
      pattern: "*__norm.nii.gz"
      mandatory: false
  - versions:
      type: file
      description: |
        File containing software versions
        Structure: [ path(versions.yml) ]
      pattern: "versions.yml"
authors:
  - "@levje"
maintainers:
  - "@levje"
