# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: reconst_noddi
description: Run NODDI modelling pipeline using AMICO from DWI data.
keywords:
  - Diffusion MRI
  - NODDI
  - Microstructure modeling
tools:
  - scilpy:
      description: The Sherbrooke Connectivity Imaging Lab (SCIL) Python dMRI processing
        toolbox.
      homepage: https://github.com/scilus/scilpy.git
      identifier: ""
  - NODDI:
      description: Method to compute neurite orientation dispersion and density imaging.
      doi: 10.1016/j.neuroimage.2012.03.072
      identifier: ""
  - AMICO:
      description: Accelerated Microstructure Imaging via Convex Optimization.
      homepage: https://github.com/daducci/AMICO
      doi: 10.1016/j.neuroimage.2014.10.026
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'test', single_end:false ]`
    - dwi:
        type: file
        description: Nifti DWI file acquired with a NODDI compatible protocol (multi-shell).
        pattern: "*.{nii,nii.gz}"
        ontologies:
          - edam: http://edamontology.org/format_4001 # NIFTI format
    - bval:
        type: file
        description: B-values in FSL format.
        pattern: "*.bval"
        ontologies: []
    - bvec:
        type: file
        description: B-vectors in FSL format.
        pattern: "*.bvec"
        ontologies: []
    - mask:
        type: file
        description: Nifti brain mask.
        pattern: "*mask.{nii,nii.gz}"
        ontologies:
          - edam: http://edamontology.org/format_4001 # NIFTI format
    - kernels:
        type: directory
        description: Folder containg kernels.
        pattern: kernels
    - para_diff:
        type: float
        description: Parallel diffusivity value (diff prior) (mm2/s).
        mandatory: false
    - iso_diff:
        type: float
        description: Isotropic diffusivity value (diff prior) (mm2/s).
        mandatory: false
args:
  - para_diff:
      type: float
      description: Axial diffusivity (AD) in the CC (mm2/s). It overwrites the input para_diff if provided.
  - iso_diff:
      type: float
      description: Mean diffusivity (MD) in ventricles (mm2/s). It overwrites the input iso_diff if provided.
  - noddi_lambda1:
      type: float
      description: First regularization parameter for NODDI fitting.
  - noddi_lambda2:
      type: float
      description: Second regularization parameter for NODDI fitting.
  - b_thr:
      type: float
      description: Limit value to consider that a b-value is on an existing shell. Above this limit, the b-value is placed on a new shell. This includes b0s values.
  - compute_only:
      type: boolean
      description: Compute kernels only.

output:
  dir:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__fit_dir.nii.gz":
          type: file
          description: Nifti file main direction.
          pattern: "*__fit_dir.{nii,nii.gz}"
          ontologies:
            - edam: http://edamontology.org/format_4001 # NIFTI format
  fwf:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__fit_FWF.nii.gz":
          type: file
          description: Nifti file for Free Water Fraction.
          pattern: "*__fit_FWF.{nii,nii.gz}"
          ontologies:
            - edam: http://edamontology.org/format_4001 # NIFTI format
  ndi:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__fit_NDI.nii.gz":
          type: file
          description: Nifti file for Neurite Density Index
          pattern: "*__fit_NDI.{nii,nii.gz}"
          ontologies:
            - edam: http://edamontology.org/format_4001 # NIFTI format
  ecvf:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__fit_ECVF.nii.gz":
          type: file
          description: Nifti file for Extra-Compartment Volume Fraction.
          pattern: "*__fit_ECVF.{nii,nii.gz}"
          ontologies:
            - edam: http://edamontology.org/format_4001 # NIFTI format
  odi:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*__fit_ODI.nii.gz":
          type: file
          description: Nifti file for Orientation Dispersion Index.
          pattern: "*__fit_ODI.{nii,nii.gz}"
          ontologies:
            - edam: http://edamontology.org/format_4001 # NIFTI format
  kernels:
    - kernels:
        type: directory
        description: Folder containing kernels.
        pattern: kernels
  versions:
    - versions.yml:
        type: file
        description: File containing software versions.
        pattern: versions.yml
        ontologies:
          - edam: http://edamontology.org/format_3750 # YAML
authors:
  - "@Manonedde"
